# Generated by Django 5.2.1 on 2025-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0002_groupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
