# Generated by Django 5.2.1 on 2025-05-26 20:12

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing StudyGroup records"""
    StudyGroup = apps.get_model('userDashboard', 'StudyGroup')
    for group in StudyGroup.objects.all():
        if group.title:
            group.slug = slugify(group.title)
        else:
            group.slug = 'untitled'
        group.save()


def reverse_populate_slugs(apps, schema_editor):
    """Reverse migration - clear slug field"""
    StudyGroup = apps.get_model('userDashboard', 'StudyGroup')
    StudyGroup.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0003_studygroup_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
