# Generated by Django 5.2.1 on 2025-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_subject_options_alter_subject_name_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about yourself and your study goals'),
        ),
    ]
